// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewField(
	field *ast.Field,
) *Field {
	c := &Field{
		field: field,
	}

	return c
}

type Fields []*Field

func (r Fields) Chunk(size int) []Fields {
	list := []Fields{}
	chunk := Fields{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = Fields{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r Fields) Compact() Fields {
	l := Fields{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r Fields) Concat(l Fields) Fields {
	return append(append(Fields{}, r...), l...)
}

func (r Fields) Copy() Fields {
	dist := make(Fields, len(r))
	copy(dist, r)
	return dist
}

func (r Fields) Count() int {
	return len(r)
}

func (r Fields) Each(f func(i int, v *Field)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r Fields) Exists() bool {
	return r != nil && len(r) > 0
}

func (r Fields) Every(f func(i int, v *Field) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r Fields) Filter(funcs ...func(i int, v *Field) bool) Fields {
	list := Fields{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r Fields) Find(funcs ...func(i int, v *Field) bool) *Field {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r Fields) FindIndex(funcs ...func(i int, v *Field) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r Fields) First() *Field {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r Fields) ForPage(pageNo int, size int) Fields {
	rLen := len(r)
	list := make(Fields, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r Fields) Get(i int) *Field {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r Fields) Has(f func(i int, v *Field) bool) bool {
	return r.Some(f)
}

func (r Fields) IsEmpty() bool {
	return len(r) == 0
}

func (r Fields) IsNotEmpty() bool {
	return len(r) > 0
}

func (r Fields) Last() *Field {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r Fields) Reverse() Fields {
	list := make(Fields, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r Fields) Some(f func(i int, v *Field) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r Fields) Take(size int) Fields {
	if len(r) > size {
		return r
	}
	return r[:size]
}

func (r Fields) Name() []string {
	l := make([]string, 0, len(r))
	for _, r := range r {
		l = append(l, r.Name())
	}
	return l
}

func (r Fields) Type() []*Type {
	l := make([]*Type, 0, len(r))
	for _, r := range r {
		l = append(l, r.Type())
	}
	return l
}

func (r Fields) Tag() []*Tag {
	l := make([]*Tag, 0, len(r))
	for _, r := range r {
		l = append(l, r.Tag())
	}
	return l
}

func (r Fields) IsExported() []bool {
	l := make([]bool, 0, len(r))
	for _, r := range r {
		l = append(l, r.IsExported())
	}
	return l
}
