// Code generated by structgen; DO NOT EDIT.

package aq

type FuncList []*Func

func (r FuncList) Chunk(size int) []FuncList {
	list := []FuncList{}
	chunk := FuncList{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = FuncList{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r FuncList) Concat(list FuncList) FuncList {
	return append(append(FuncList{}, r...), list...)
}

func (r FuncList) Copy() FuncList {
	dist := make(FuncList, len(r))
	copy(dist, r)
	return dist
}

func (r FuncList) Count() int {
	return len(r)
}

func (r FuncList) Each(f func(i int, v *Func)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r FuncList) Exists() bool {
	return r != nil && len(r) > 0
}

func (r FuncList) Every(f func(i int, v *Func) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r FuncList) Filter(funcs ...func(i int, v *Func) bool) FuncList {
	list := FuncList{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r FuncList) Find(funcs ...func(i int, v *Func) bool) *Func {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r FuncList) FindIndex(funcs ...func(i int, v *Func) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r FuncList) First() *Func {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r FuncList) ForPage(pageNo int, size int) FuncList {
	rLen := len(r)
	list := make(FuncList, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r FuncList) Get(i int) *Func {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r FuncList) IsEmpty() bool {
	return len(r) == 0
}

func (r FuncList) IsNotEmpty() bool {
	return len(r) > 0
}

func (r FuncList) Last() *Func {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r FuncList) Reverse() FuncList {
	list := make(FuncList, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r FuncList) Some(f func(i int, v *Func) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r FuncList) Take(size int) FuncList {
	if len(r) > size {
		return r
	}
	return r[:size]
}
