// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewImport(
	importSpec *ast.ImportSpec,
) *Import {
	c := &Import{
		importSpec: importSpec,
	}

	return c
}

type Imports []*Import

func (r Imports) Chunk(size int) []Imports {
	list := []Imports{}
	chunk := Imports{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = Imports{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r Imports) Compact() Imports {
	l := Imports{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r Imports) Concat(l Imports) Imports {
	return append(append(Imports{}, r...), l...)
}

func (r Imports) Copy() Imports {
	dist := make(Imports, len(r))
	copy(dist, r)
	return dist
}

func (r Imports) Count() int {
	return len(r)
}

func (r Imports) Each(f func(i int, v *Import)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r Imports) Exists() bool {
	return r != nil && len(r) > 0
}

func (r Imports) Every(f func(i int, v *Import) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r Imports) Filter(funcs ...func(i int, v *Import) bool) Imports {
	list := Imports{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r Imports) Find(funcs ...func(i int, v *Import) bool) *Import {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r Imports) FindIndex(funcs ...func(i int, v *Import) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r Imports) First() *Import {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r Imports) ForPage(pageNo int, size int) Imports {
	rLen := len(r)
	list := make(Imports, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r Imports) Get(i int) *Import {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r Imports) Has(f func(i int, v *Import) bool) bool {
	return r.Some(f)
}

func (r Imports) IsEmpty() bool {
	return len(r) == 0
}

func (r Imports) IsNotEmpty() bool {
	return len(r) > 0
}

func (r Imports) Last() *Import {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r Imports) Reverse() Imports {
	list := make(Imports, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r Imports) Some(f func(i int, v *Import) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r Imports) Take(size int) Imports {
	if len(r) > size {
		return r
	}
	return r[:size]
}

func (r Imports) ImportSpecs() []*ast.ImportSpec {
	l := make([]*ast.ImportSpec, 0, len(r))
	for _, r := range r {
		l = append(l, r.importSpec)
	}
	return l
}

func (r Imports) Name() []string {
	l := make([]string, 0, len(r))
	for _, r := range r {
		l = append(l, r.Name())
	}
	return l
}

func (r Imports) Path() []string {
	l := make([]string, 0, len(r))
	for _, r := range r {
		l = append(l, r.Path())
	}
	return l
}
