// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewImportSpec(
	importSpec *ast.ImportSpec,
) *ImportSpec {
	c := &ImportSpec{
		importSpec: importSpec,
	}

	return c
}

type ImportSpecs []*ImportSpec

func (r ImportSpecs) Chunk(size int) []ImportSpecs {
	list := []ImportSpecs{}
	chunk := ImportSpecs{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = ImportSpecs{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r ImportSpecs) Compact() ImportSpecs {
	l := ImportSpecs{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r ImportSpecs) Concat(l ImportSpecs) ImportSpecs {
	return append(append(ImportSpecs{}, r...), l...)
}

func (r ImportSpecs) Copy() ImportSpecs {
	dist := make(ImportSpecs, len(r))
	copy(dist, r)
	return dist
}

func (r ImportSpecs) Count() int {
	return len(r)
}

func (r ImportSpecs) Each(f func(i int, v *ImportSpec)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r ImportSpecs) Exists() bool {
	return r != nil && len(r) > 0
}

func (r ImportSpecs) Every(f func(i int, v *ImportSpec) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r ImportSpecs) Filter(funcs ...func(i int, v *ImportSpec) bool) ImportSpecs {
	list := ImportSpecs{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r ImportSpecs) Find(funcs ...func(i int, v *ImportSpec) bool) *ImportSpec {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r ImportSpecs) FindIndex(funcs ...func(i int, v *ImportSpec) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r ImportSpecs) First() *ImportSpec {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r ImportSpecs) ForPage(pageNo int, size int) ImportSpecs {
	rLen := len(r)
	list := make(ImportSpecs, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r ImportSpecs) Get(i int) *ImportSpec {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r ImportSpecs) Has(f func(i int, v *ImportSpec) bool) bool {
	return r.Some(f)
}

func (r ImportSpecs) IsEmpty() bool {
	return len(r) == 0
}

func (r ImportSpecs) IsNotEmpty() bool {
	return len(r) > 0
}

func (r ImportSpecs) Last() *ImportSpec {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r ImportSpecs) Reverse() ImportSpecs {
	list := make(ImportSpecs, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r ImportSpecs) Some(f func(i int, v *ImportSpec) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r ImportSpecs) Take(size int) ImportSpecs {
	if len(r) > size {
		return r
	}
	return r[:size]
}

func (r ImportSpecs) Names() []string {
	l := make([]string, 0, len(r))
	for _, r := range r {
		l = append(l, r.Name())
	}
	return l
}

func (r ImportSpecs) Paths() []string {
	l := make([]string, 0, len(r))
	for _, r := range r {
		l = append(l, r.Path())
	}
	return l
}
