// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewInterfaceSpec(
	aq *AQ,
	file *File,
	spec *ast.TypeSpec,
	typ *ast.InterfaceType,
) *InterfaceSpec {
	c := &InterfaceSpec{
		aq:   aq,
		file: file,
		spec: spec,
		typ:  typ,
	}

	return c
}

type InterfaceSpecs []*InterfaceSpec

func (r InterfaceSpecs) Chunk(size int) []InterfaceSpecs {
	list := []InterfaceSpecs{}
	chunk := InterfaceSpecs{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = InterfaceSpecs{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r InterfaceSpecs) Compact() InterfaceSpecs {
	l := InterfaceSpecs{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r InterfaceSpecs) Concat(l InterfaceSpecs) InterfaceSpecs {
	return append(append(InterfaceSpecs{}, r...), l...)
}

func (r InterfaceSpecs) Copy() InterfaceSpecs {
	dist := make(InterfaceSpecs, len(r))
	copy(dist, r)
	return dist
}

func (r InterfaceSpecs) Count() int {
	return len(r)
}

func (r InterfaceSpecs) Each(f func(i int, v *InterfaceSpec)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r InterfaceSpecs) Exists() bool {
	return r != nil && len(r) > 0
}

func (r InterfaceSpecs) Every(f func(i int, v *InterfaceSpec) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r InterfaceSpecs) Filter(funcs ...func(i int, v *InterfaceSpec) bool) InterfaceSpecs {
	list := InterfaceSpecs{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r InterfaceSpecs) Find(funcs ...func(i int, v *InterfaceSpec) bool) *InterfaceSpec {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r InterfaceSpecs) FindIndex(funcs ...func(i int, v *InterfaceSpec) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r InterfaceSpecs) First() *InterfaceSpec {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r InterfaceSpecs) ForPage(pageNo int, size int) InterfaceSpecs {
	rLen := len(r)
	list := make(InterfaceSpecs, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r InterfaceSpecs) Get(i int) *InterfaceSpec {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r InterfaceSpecs) Has(f func(i int, v *InterfaceSpec) bool) bool {
	return r.Some(f)
}

func (r InterfaceSpecs) IsEmpty() bool {
	return len(r) == 0
}

func (r InterfaceSpecs) IsNotEmpty() bool {
	return len(r) > 0
}

func (r InterfaceSpecs) Last() *InterfaceSpec {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r InterfaceSpecs) Reverse() InterfaceSpecs {
	list := make(InterfaceSpecs, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r InterfaceSpecs) Some(f func(i int, v *InterfaceSpec) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r InterfaceSpecs) Take(size int) InterfaceSpecs {
	if len(r) > size {
		return r
	}
	return r[:size]
}

func (r InterfaceSpecs) Names() []string {
	l := make([]string, 0, len(r))
	for _, r := range r {
		l = append(l, r.Name())
	}
	return l
}
