// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewInterfaceType(
	i *AQ,
	typ *ast.InterfaceType,
) *InterfaceType {
	c := &InterfaceType{
		i:   i,
		typ: typ,
	}

	return c
}

type InterfaceTypes []*InterfaceType

func (r InterfaceTypes) Chunk(size int) []InterfaceTypes {
	list := []InterfaceTypes{}
	chunk := InterfaceTypes{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = InterfaceTypes{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r InterfaceTypes) Compact() InterfaceTypes {
	l := InterfaceTypes{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r InterfaceTypes) Concat(l InterfaceTypes) InterfaceTypes {
	return append(append(InterfaceTypes{}, r...), l...)
}

func (r InterfaceTypes) Copy() InterfaceTypes {
	dist := make(InterfaceTypes, len(r))
	copy(dist, r)
	return dist
}

func (r InterfaceTypes) Count() int {
	return len(r)
}

func (r InterfaceTypes) Each(f func(i int, v *InterfaceType)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r InterfaceTypes) Exists() bool {
	return r != nil && len(r) > 0
}

func (r InterfaceTypes) Every(f func(i int, v *InterfaceType) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r InterfaceTypes) Filter(funcs ...func(i int, v *InterfaceType) bool) InterfaceTypes {
	list := InterfaceTypes{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r InterfaceTypes) Find(funcs ...func(i int, v *InterfaceType) bool) *InterfaceType {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r InterfaceTypes) FindIndex(funcs ...func(i int, v *InterfaceType) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r InterfaceTypes) First() *InterfaceType {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r InterfaceTypes) ForPage(pageNo int, size int) InterfaceTypes {
	rLen := len(r)
	list := make(InterfaceTypes, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r InterfaceTypes) Get(i int) *InterfaceType {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r InterfaceTypes) Has(f func(i int, v *InterfaceType) bool) bool {
	return r.Some(f)
}

func (r InterfaceTypes) IsEmpty() bool {
	return len(r) == 0
}

func (r InterfaceTypes) IsNotEmpty() bool {
	return len(r) > 0
}

func (r InterfaceTypes) Last() *InterfaceType {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r InterfaceTypes) Reverse() InterfaceTypes {
	list := make(InterfaceTypes, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r InterfaceTypes) Some(f func(i int, v *InterfaceType) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r InterfaceTypes) Take(size int) InterfaceTypes {
	if len(r) > size {
		return r
	}
	return r[:size]
}
