// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewStructSpec(
	instance *AQ,
	file *File,
	typeSpec *ast.TypeSpec,
	structType *ast.StructType,
) *StructSpec {
	c := &StructSpec{
		instance:   instance,
		file:       file,
		typeSpec:   typeSpec,
		structType: structType,
	}

	return c
}

type StructSpecs []*StructSpec

func (r StructSpecs) Chunk(size int) []StructSpecs {
	list := []StructSpecs{}
	chunk := StructSpecs{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = StructSpecs{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r StructSpecs) Compact() StructSpecs {
	l := StructSpecs{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r StructSpecs) Concat(l StructSpecs) StructSpecs {
	return append(append(StructSpecs{}, r...), l...)
}

func (r StructSpecs) Copy() StructSpecs {
	dist := make(StructSpecs, len(r))
	copy(dist, r)
	return dist
}

func (r StructSpecs) Count() int {
	return len(r)
}

func (r StructSpecs) Each(f func(i int, v *StructSpec)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r StructSpecs) Exists() bool {
	return r != nil && len(r) > 0
}

func (r StructSpecs) Every(f func(i int, v *StructSpec) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r StructSpecs) Filter(funcs ...func(i int, v *StructSpec) bool) StructSpecs {
	list := StructSpecs{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r StructSpecs) Find(funcs ...func(i int, v *StructSpec) bool) *StructSpec {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r StructSpecs) FindIndex(funcs ...func(i int, v *StructSpec) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r StructSpecs) First() *StructSpec {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r StructSpecs) ForPage(pageNo int, size int) StructSpecs {
	rLen := len(r)
	list := make(StructSpecs, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r StructSpecs) Get(i int) *StructSpec {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r StructSpecs) Has(f func(i int, v *StructSpec) bool) bool {
	return r.Some(f)
}

func (r StructSpecs) IsEmpty() bool {
	return len(r) == 0
}

func (r StructSpecs) IsNotEmpty() bool {
	return len(r) > 0
}

func (r StructSpecs) Last() *StructSpec {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r StructSpecs) Reverse() StructSpecs {
	list := make(StructSpecs, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r StructSpecs) Some(f func(i int, v *StructSpec) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r StructSpecs) Take(size int) StructSpecs {
	if len(r) > size {
		return r
	}
	return r[:size]
}
