// Code generated by structgen; DO NOT EDIT.

package aq

import (
	"go/ast"
)

func NewStruct(
	instance *AQ,
	file *File,
	typeSpec *ast.TypeSpec,
	structType *ast.StructType,
) *Struct {
	c := &Struct{
		instance:   instance,
		file:       file,
		typeSpec:   typeSpec,
		structType: structType,
	}

	return c
}

type Structs []*Struct

func (r Structs) Chunk(size int) []Structs {
	list := []Structs{}
	chunk := Structs{}
	for _, v := range r {
		chunk := append(chunk, v)
		if len(chunk) >= size {
			list = append(list, chunk)
			chunk = Structs{}
		}
	}
	if len(chunk) > 0 {
		list = append(list, chunk)
	}
	return list
}

func (r Structs) Compact() Structs {
	l := Structs{}
	for _, v := range r {
		if v == nil {
			l = append(l, v)
		}
	}
	return l
}

func (r Structs) Concat(l Structs) Structs {
	return append(append(Structs{}, r...), l...)
}

func (r Structs) Copy() Structs {
	dist := make(Structs, len(r))
	copy(dist, r)
	return dist
}

func (r Structs) Count() int {
	return len(r)
}

func (r Structs) Each(f func(i int, v *Struct)) {
	for i, v := range r {
		f(i, v)
	}
}

func (r Structs) Exists() bool {
	return r != nil && len(r) > 0
}

func (r Structs) Every(f func(i int, v *Struct) bool) bool {
	for i, v := range r {
		if !f(i, v) {
			return false
		}
	}
	return true
}

func (r Structs) Filter(funcs ...func(i int, v *Struct) bool) Structs {
	list := Structs{}
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		list = append(list, v)
	}
	return list
}

func (r Structs) Find(funcs ...func(i int, v *Struct) bool) *Struct {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return v
	}
	return nil
}

func (r Structs) FindIndex(funcs ...func(i int, v *Struct) bool) int {
L:
	for i, v := range r {
		for _, f := range funcs {
			if !f(i, v) {
				continue L
			}
		}
		return i
	}
	return -1
}

func (r Structs) First() *Struct {
	if len(r) == 0 {
		return nil
	}
	return r[0]
}

func (r Structs) ForPage(pageNo int, size int) Structs {
	rLen := len(r)
	list := make(Structs, 0, size)
	for i, k := pageNo*size, 0; i < rLen && k < size; i, k = i+1, k+1 {
		list = append(list, r[i])
	}
	return list
}

func (r Structs) Get(i int) *Struct {
	if 0 <= i && i < len(r) {
		return r[i]
	}
	return nil
}

func (r Structs) Has(f func(i int, v *Struct) bool) bool {
	return r.Some(f)
}

func (r Structs) IsEmpty() bool {
	return len(r) == 0
}

func (r Structs) IsNotEmpty() bool {
	return len(r) > 0
}

func (r Structs) Last() *Struct {
	if len(r) == 0 {
		return nil
	}
	return r[len(r)-1]
}

func (r Structs) Reverse() Structs {
	list := make(Structs, 0, len(r))
	for i := len(r) - 1; i >= 0; i-- {
		list = append(list, r[i])
	}
	return list
}

func (r Structs) Some(f func(i int, v *Struct) bool) bool {
	for i, v := range r {
		if f(i, v) {
			return true
		}
	}
	return false
}

func (r Structs) Take(size int) Structs {
	if len(r) > size {
		return r
	}
	return r[:size]
}

func (r Structs) Instances() []*AQ {
	l := make([]*AQ, 0, len(r))
	for _, r := range r {
		l = append(l, r.instance)
	}
	return l
}

func (r Structs) Files() []*File {
	l := make([]*File, 0, len(r))
	for _, r := range r {
		l = append(l, r.file)
	}
	return l
}

func (r Structs) TypeSpecs() []*ast.TypeSpec {
	l := make([]*ast.TypeSpec, 0, len(r))
	for _, r := range r {
		l = append(l, r.typeSpec)
	}
	return l
}

func (r Structs) StructTypes() []*ast.StructType {
	l := make([]*ast.StructType, 0, len(r))
	for _, r := range r {
		l = append(l, r.structType)
	}
	return l
}
